"""Add string lengtsh

Revision ID: 317e55321763
Revises: d29f54375340
Create Date: 2024-05-28 14:58:38.583555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '317e55321763'
down_revision: Union[str, None] = 'd29f54375340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedure_type_association')
    op.add_column('procedures', sa.Column('type_procedure_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'procedures', 'type_procedures', ['type_procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_column('procedures', 'type_procedure_id')
    op.create_table('procedure_type_association',
    sa.Column('procedure_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_procedure_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name='procedure_type_association_ibfk_1'),
    sa.ForeignKeyConstraint(['type_procedure_id'], ['type_procedures.id'], name='procedure_type_association_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
